---
author: |
  Omar Laurino, Gerard Lemson,\
  Tom Donaldson
title: VODML Mapping
subtitle: Ongoing Interoperable Implementations
date: May 28 2018
venue: Victoria Interop 2018
theme: sky
css:
  - css/custom.css

...
